apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: tap-dotnet-weatherforecast
  annotations:
    "backstage.io/kubernetes-label-selector": "app.kubernetes.io/part-of=tap-dotnet-weatherforecast"
spec:
  type: service
  lifecycle: experimental
  owner: default-team
