apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: tap-dotnet-weatherforecast
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: tap-dotnet-weatherforecast
spec:
  source:
    git:
      url: https://github.com/ShawkyZ/tap-dotnet-weatherforecast
      ref:
        branch: main
